### ISSUE TITLE
Impossible to run it

### ISSUE THREAD

**Issue by P3lUZa** [bitsoex/bitso-java#1]
I tried to run this repo on Netbeans 8, and even with no modifications it throws:

---

Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project bitso-java: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

---

*Then I tried on Eclipse (adding the key values):

---

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/json/JSONObject : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at com.bitso.examples.BitsoJavaExample.main(BitsoJavaExample.java:35)

I'm using OpenJDK 7 64 bits. As I said I'm using the pure code of this repo, trying to run the BitsoJavaExample.java class. It doesn't work!

**Comment by P3lUZa** [comment]
Ok, after reading the eclipse error I managed to make it work (I wasted a lot of time trying on netbeans). It looks like the problem was that I was using OpenJDK 7 and your code is only supported by OpenJDK 8. Anyway, I would suggest to specify that on the Readme, since it is not obvious.

**Comment by vogelito** [comment]
Thanks @P3lUZa 

Sorry you wasted a lot of time. I just made an update to the README to reflect that.
