### ISSUE TITLE
I can't run the simplest example

### ISSUE THREAD

**Issue by luiscarlos-gonzalez** [bitsoex/bitso-java#28]
I'm trying to use bitso-java on android but i get the following error:
```
05-25 20:46:18.403 6783-6783/com.kentverger.bitsoearnings E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.kentverger.bitsoearnings, PID: 6783
                                                                            java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/client/HttpClients;
                                                                                at com.bitso.http.BlockingHttpClient.sendGet(BlockingHttpClient.java:104)
                                                                                at com.bitso.Bitso.sendBitsoGet(Bitso.java:571)
                                                                                at com.bitso.Bitso.getUserAccountBalance(Bitso.java:148)
                                                                                at com.kentverger.bitsoearnings.MainActivity.onCreate(MainActivity.java:14)
                                                                                at android.app.Activity.performCreate(Activity.java:6237)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                             Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.impl.client.HttpClients" on path: DexPathList[[zip file "/data/app/com.kentverger.bitsoearnings-2/base.apk"],nativeLibraryDirectories=[/data/app/com.kentverger.bitsoearnings-2/lib/x86_64, /vendor/lib64, /system/lib64]]
                                                                                at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                at com.bitso.http.BlockingHttpClient.sendGet(BlockingHttpClient.java:104) 
                                                                                at com.bitso.Bitso.sendBitsoGet(Bitso.java:571) 
                                                                                at com.bitso.Bitso.getUserAccountBalance(Bitso.java:148) 
                                                                                at com.kentverger.bitsoearnings.MainActivity.onCreate(MainActivity.java:14) 
                                                                                at android.app.Activity.performCreate(Activity.java:6237) 
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:148) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                            	Suppressed: java.lang.ClassNotFoundException: org.apache.http.impl.client.HttpClients
                                                                                at java.lang.Class.classForName(Native Method)
                                                                                at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                		... 17 more
```
this is my app.gradle:
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.kentverger.bitsoearnings"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        jackOptions {
            enabled true
        }

        packagingOptions {
            exclude 'META-INF/INDEX.LIST'
            exclude 'META-INF/LICENSE'
        }

        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }

        dexOptions {
            incremental true
            javaMaxHeapSize "4g"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.1.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
    compile 'com.bitso:bitso-java:3.0.3'
}
```
This is my Activity:
```
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Bitso bitso = new Bitso("xxxxxx", "xxxxxxxx");
        System.out.println(bitso.getUserAccountBalance());
        setContentView(R.layout.activity_main);
    }
}
```

The error says that don't found the HttpClients class, I think that I have something misconfigured, there is an error on the readme file?

Can you help me to get starting using the bitso java library?

**Comment by nvcruzhe** [comment]
Please check the documentation, there a is new info about how to integrate it with jitpack and gradle easier.
